// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.icc.web.netty.gprc.protobuf;

public interface RequestHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icc.web.netty.protobuf3.RequestHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
