// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.icc.web.netty.gprc.protobuf;

/**
 * Protobuf type {@code com.icc.web.netty.protobuf3.RequestHeaderList}
 */
public  final class RequestHeaderList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.icc.web.netty.protobuf3.RequestHeaderList)
        RequestHeaderListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestHeaderList.newBuilder() to construct.
  private RequestHeaderList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestHeaderList() {
    request_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestHeaderList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              request_ = new java.util.ArrayList<RequestHeader>();
              mutable_bitField0_ |= 0x00000001;
            }
            request_.add(
                input.readMessage(RequestHeader.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        request_ = java.util.Collections.unmodifiableList(request_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataInfo.internal_static_com_icc_web_netty_protobuf3_RequestHeaderList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataInfo.internal_static_com_icc_web_netty_protobuf3_RequestHeaderList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RequestHeaderList.class, RequestHeaderList.Builder.class);
  }

  public static final int REQUEST_FIELD_NUMBER = 1;
  private java.util.List<RequestHeader> request_;
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  public java.util.List<RequestHeader> getRequestList() {
    return request_;
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  public java.util.List<? extends RequestHeaderOrBuilder>
      getRequestOrBuilderList() {
    return request_;
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  public int getRequestCount() {
    return request_.size();
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  public RequestHeader getRequest(int index) {
    return request_.get(index);
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  public RequestHeaderOrBuilder getRequestOrBuilder(
      int index) {
    return request_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < request_.size(); i++) {
      output.writeMessage(1, request_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < request_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, request_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RequestHeaderList)) {
      return super.equals(obj);
    }
    RequestHeaderList other = (RequestHeaderList) obj;

    if (!getRequestList()
        .equals(other.getRequestList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRequestCount() > 0) {
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequestList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RequestHeaderList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHeaderList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHeaderList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHeaderList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHeaderList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RequestHeaderList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RequestHeaderList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestHeaderList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestHeaderList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RequestHeaderList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RequestHeaderList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RequestHeaderList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RequestHeaderList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.icc.web.netty.protobuf3.RequestHeaderList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.icc.web.netty.protobuf3.RequestHeaderList)
          RequestHeaderListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_RequestHeaderList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_RequestHeaderList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestHeaderList.class, RequestHeaderList.Builder.class);
    }

    // Construct using com.icc.web.netty.protobuf3.RequestHeaderList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (requestBuilder_ == null) {
        request_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        requestBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_RequestHeaderList_descriptor;
    }

    @Override
    public RequestHeaderList getDefaultInstanceForType() {
      return RequestHeaderList.getDefaultInstance();
    }

    @Override
    public RequestHeaderList build() {
      RequestHeaderList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public RequestHeaderList buildPartial() {
      RequestHeaderList result = new RequestHeaderList(this);
      int from_bitField0_ = bitField0_;
      if (requestBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          request_ = java.util.Collections.unmodifiableList(request_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.request_ = request_;
      } else {
        result.request_ = requestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RequestHeaderList) {
        return mergeFrom((RequestHeaderList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RequestHeaderList other) {
      if (other == RequestHeaderList.getDefaultInstance()) return this;
      if (requestBuilder_ == null) {
        if (!other.request_.isEmpty()) {
          if (request_.isEmpty()) {
            request_ = other.request_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRequestIsMutable();
            request_.addAll(other.request_);
          }
          onChanged();
        }
      } else {
        if (!other.request_.isEmpty()) {
          if (requestBuilder_.isEmpty()) {
            requestBuilder_.dispose();
            requestBuilder_ = null;
            request_ = other.request_;
            bitField0_ = (bitField0_ & ~0x00000001);
            requestBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRequestFieldBuilder() : null;
          } else {
            requestBuilder_.addAllMessages(other.request_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RequestHeaderList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RequestHeaderList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<RequestHeader> request_ =
      java.util.Collections.emptyList();
    private void ensureRequestIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        request_ = new java.util.ArrayList<RequestHeader>(request_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            RequestHeader, RequestHeader.Builder, RequestHeaderOrBuilder> requestBuilder_;

    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public java.util.List<RequestHeader> getRequestList() {
      if (requestBuilder_ == null) {
        return java.util.Collections.unmodifiableList(request_);
      } else {
        return requestBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public int getRequestCount() {
      if (requestBuilder_ == null) {
        return request_.size();
      } else {
        return requestBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public RequestHeader getRequest(int index) {
      if (requestBuilder_ == null) {
        return request_.get(index);
      } else {
        return requestBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder setRequest(
        int index, RequestHeader value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestIsMutable();
        request_.set(index, value);
        onChanged();
      } else {
        requestBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder setRequest(
        int index, RequestHeader.Builder builderForValue) {
      if (requestBuilder_ == null) {
        ensureRequestIsMutable();
        request_.set(index, builderForValue.build());
        onChanged();
      } else {
        requestBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder addRequest(RequestHeader value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestIsMutable();
        request_.add(value);
        onChanged();
      } else {
        requestBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder addRequest(
        int index, RequestHeader value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRequestIsMutable();
        request_.add(index, value);
        onChanged();
      } else {
        requestBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder addRequest(
        RequestHeader.Builder builderForValue) {
      if (requestBuilder_ == null) {
        ensureRequestIsMutable();
        request_.add(builderForValue.build());
        onChanged();
      } else {
        requestBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder addRequest(
        int index, RequestHeader.Builder builderForValue) {
      if (requestBuilder_ == null) {
        ensureRequestIsMutable();
        request_.add(index, builderForValue.build());
        onChanged();
      } else {
        requestBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder addAllRequest(
        Iterable<? extends RequestHeader> values) {
      if (requestBuilder_ == null) {
        ensureRequestIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, request_);
        onChanged();
      } else {
        requestBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        request_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        requestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public Builder removeRequest(int index) {
      if (requestBuilder_ == null) {
        ensureRequestIsMutable();
        request_.remove(index);
        onChanged();
      } else {
        requestBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public RequestHeader.Builder getRequestBuilder(
        int index) {
      return getRequestFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public RequestHeaderOrBuilder getRequestOrBuilder(
        int index) {
      if (requestBuilder_ == null) {
        return request_.get(index);  } else {
        return requestBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public java.util.List<? extends RequestHeaderOrBuilder>
         getRequestOrBuilderList() {
      if (requestBuilder_ != null) {
        return requestBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(request_);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public RequestHeader.Builder addRequestBuilder() {
      return getRequestFieldBuilder().addBuilder(
          RequestHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public RequestHeader.Builder addRequestBuilder(
        int index) {
      return getRequestFieldBuilder().addBuilder(
          index, RequestHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
     */
    public java.util.List<RequestHeader.Builder>
         getRequestBuilderList() {
      return getRequestFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            RequestHeader, RequestHeader.Builder, RequestHeaderOrBuilder>
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        requestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                RequestHeader, RequestHeader.Builder, RequestHeaderOrBuilder>(
                request_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      return requestBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.icc.web.netty.protobuf3.RequestHeaderList)
  }

  // @@protoc_insertion_point(class_scope:com.icc.web.netty.protobuf3.RequestHeaderList)
  private static final RequestHeaderList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RequestHeaderList();
  }

  public static RequestHeaderList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestHeaderList>
      PARSER = new com.google.protobuf.AbstractParser<RequestHeaderList>() {
    @Override
    public RequestHeaderList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestHeaderList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestHeaderList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RequestHeaderList> getParserForType() {
    return PARSER;
  }

  @Override
  public RequestHeaderList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

