// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.icc.web.netty.gprc.protobuf;

public interface RequestHeaderListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icc.web.netty.protobuf3.RequestHeaderList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  java.util.List<RequestHeader>
      getRequestList();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  RequestHeader getRequest(int index);
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  int getRequestCount();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  java.util.List<? extends RequestHeaderOrBuilder>
      getRequestOrBuilderList();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.RequestHeader request = 1;</code>
   */
  RequestHeaderOrBuilder getRequestOrBuilder(
          int index);
}
