// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.icc.web.netty.gprc.protobuf;

/**
 * Protobuf type {@code com.icc.web.netty.protobuf3.ResponseHeaderList}
 */
public  final class ResponseHeaderList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.icc.web.netty.protobuf3.ResponseHeaderList)
        ResponseHeaderListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseHeaderList.newBuilder() to construct.
  private ResponseHeaderList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseHeaderList() {
    response_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseHeaderList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              response_ = new java.util.ArrayList<ResponseHeader>();
              mutable_bitField0_ |= 0x00000001;
            }
            response_.add(
                input.readMessage(ResponseHeader.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        response_ = java.util.Collections.unmodifiableList(response_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return DataInfo.internal_static_com_icc_web_netty_protobuf3_ResponseHeaderList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return DataInfo.internal_static_com_icc_web_netty_protobuf3_ResponseHeaderList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ResponseHeaderList.class, ResponseHeaderList.Builder.class);
  }

  public static final int RESPONSE_FIELD_NUMBER = 1;
  private java.util.List<ResponseHeader> response_;
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  public java.util.List<ResponseHeader> getResponseList() {
    return response_;
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  public java.util.List<? extends ResponseHeaderOrBuilder>
      getResponseOrBuilderList() {
    return response_;
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  public int getResponseCount() {
    return response_.size();
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  public ResponseHeader getResponse(int index) {
    return response_.get(index);
  }
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  public ResponseHeaderOrBuilder getResponseOrBuilder(
      int index) {
    return response_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < response_.size(); i++) {
      output.writeMessage(1, response_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < response_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, response_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ResponseHeaderList)) {
      return super.equals(obj);
    }
    ResponseHeaderList other = (ResponseHeaderList) obj;

    if (!getResponseList()
        .equals(other.getResponseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResponseCount() > 0) {
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ResponseHeaderList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseHeaderList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseHeaderList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseHeaderList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseHeaderList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ResponseHeaderList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ResponseHeaderList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseHeaderList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseHeaderList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ResponseHeaderList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ResponseHeaderList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ResponseHeaderList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ResponseHeaderList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.icc.web.netty.protobuf3.ResponseHeaderList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.icc.web.netty.protobuf3.ResponseHeaderList)
          ResponseHeaderListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_ResponseHeaderList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_ResponseHeaderList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseHeaderList.class, ResponseHeaderList.Builder.class);
    }

    // Construct using com.icc.web.netty.protobuf3.ResponseHeaderList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResponseFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        responseBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return DataInfo.internal_static_com_icc_web_netty_protobuf3_ResponseHeaderList_descriptor;
    }

    @Override
    public ResponseHeaderList getDefaultInstanceForType() {
      return ResponseHeaderList.getDefaultInstance();
    }

    @Override
    public ResponseHeaderList build() {
      ResponseHeaderList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ResponseHeaderList buildPartial() {
      ResponseHeaderList result = new ResponseHeaderList(this);
      int from_bitField0_ = bitField0_;
      if (responseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          response_ = java.util.Collections.unmodifiableList(response_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.response_ = response_;
      } else {
        result.response_ = responseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ResponseHeaderList) {
        return mergeFrom((ResponseHeaderList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ResponseHeaderList other) {
      if (other == ResponseHeaderList.getDefaultInstance()) return this;
      if (responseBuilder_ == null) {
        if (!other.response_.isEmpty()) {
          if (response_.isEmpty()) {
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResponseIsMutable();
            response_.addAll(other.response_);
          }
          onChanged();
        }
      } else {
        if (!other.response_.isEmpty()) {
          if (responseBuilder_.isEmpty()) {
            responseBuilder_.dispose();
            responseBuilder_ = null;
            response_ = other.response_;
            bitField0_ = (bitField0_ & ~0x00000001);
            responseBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResponseFieldBuilder() : null;
          } else {
            responseBuilder_.addAllMessages(other.response_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ResponseHeaderList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ResponseHeaderList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ResponseHeader> response_ =
      java.util.Collections.emptyList();
    private void ensureResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        response_ = new java.util.ArrayList<ResponseHeader>(response_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder> responseBuilder_;

    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public java.util.List<ResponseHeader> getResponseList() {
      if (responseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(response_);
      } else {
        return responseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public int getResponseCount() {
      if (responseBuilder_ == null) {
        return response_.size();
      } else {
        return responseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public ResponseHeader getResponse(int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);
      } else {
        return responseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder setResponse(
        int index, ResponseHeader value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.set(index, value);
        onChanged();
      } else {
        responseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder setResponse(
        int index, ResponseHeader.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.set(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder addResponse(ResponseHeader value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(value);
        onChanged();
      } else {
        responseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder addResponse(
        int index, ResponseHeader value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResponseIsMutable();
        response_.add(index, value);
        onChanged();
      } else {
        responseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder addResponse(
        ResponseHeader.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder addResponse(
        int index, ResponseHeader.Builder builderForValue) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.add(index, builderForValue.build());
        onChanged();
      } else {
        responseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder addAllResponse(
        Iterable<? extends ResponseHeader> values) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, response_);
        onChanged();
      } else {
        responseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        response_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public Builder removeResponse(int index) {
      if (responseBuilder_ == null) {
        ensureResponseIsMutable();
        response_.remove(index);
        onChanged();
      } else {
        responseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public ResponseHeader.Builder getResponseBuilder(
        int index) {
      return getResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public ResponseHeaderOrBuilder getResponseOrBuilder(
        int index) {
      if (responseBuilder_ == null) {
        return response_.get(index);  } else {
        return responseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public java.util.List<? extends ResponseHeaderOrBuilder>
         getResponseOrBuilderList() {
      if (responseBuilder_ != null) {
        return responseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(response_);
      }
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public ResponseHeader.Builder addResponseBuilder() {
      return getResponseFieldBuilder().addBuilder(
          ResponseHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public ResponseHeader.Builder addResponseBuilder(
        int index) {
      return getResponseFieldBuilder().addBuilder(
          index, ResponseHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
     */
    public java.util.List<ResponseHeader.Builder>
         getResponseBuilderList() {
      return getResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder>
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        responseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                ResponseHeader, ResponseHeader.Builder, ResponseHeaderOrBuilder>(
                response_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      return responseBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.icc.web.netty.protobuf3.ResponseHeaderList)
  }

  // @@protoc_insertion_point(class_scope:com.icc.web.netty.protobuf3.ResponseHeaderList)
  private static final ResponseHeaderList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ResponseHeaderList();
  }

  public static ResponseHeaderList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseHeaderList>
      PARSER = new com.google.protobuf.AbstractParser<ResponseHeaderList>() {
    @Override
    public ResponseHeaderList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseHeaderList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseHeaderList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ResponseHeaderList> getParserForType() {
    return PARSER;
  }

  @Override
  public ResponseHeaderList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

