// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.icc.web.netty.gprc.protobuf;

public interface ResponseHeaderListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icc.web.netty.protobuf3.ResponseHeaderList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  java.util.List<ResponseHeader>
      getResponseList();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  ResponseHeader getResponse(int index);
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  int getResponseCount();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  java.util.List<? extends ResponseHeaderOrBuilder>
      getResponseOrBuilderList();
  /**
   * <code>repeated .com.icc.web.netty.protobuf3.ResponseHeader response = 1;</code>
   */
  ResponseHeaderOrBuilder getResponseOrBuilder(
          int index);
}
